gui:
  showIcons: true
  nerdFontsVersion: "3"
  border: rounded
  showBottomLine: false
  showPanelJumps: false
  theme:
    activeBorderColor:
      - "#a6e3a1"
      - bold
    inactiveBorderColor:
      - "#585b70"
    searchingActiveBorderColor:
      - "#f9e2af"
      - bold
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    cherryPickedCommitBgColor:
      - "#313244"
    markedBaseCommitFgColor:
      - "#a6e3a1"
    markedBaseCommitBgColor:
      - "#313244"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --

os:
  editPreset: nvim

keybinding:
  universal:
    quit: q
    quit-alt1: <c-c>

promptToReturnFromSubprocess: false
