# macOS dependencies for the configurations in this repository.
brew "chezmoi"
brew "git"
brew "git-lfs"
brew "neovim"
brew "lazygit"
brew "jq"
brew "ripgrep"
brew "direnv"
brew "zoxide"
brew "lsd"
brew "fastfetch"
brew "powerlevel10k"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "zsh-completions"
brew "python@3.12"

cask "ghostty"
cask "karabiner-elements"
cask "visual-studio-code"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
