# macOS providers for the CLIs inventoried on Linux (2026-10-08).
# Non-Homebrew tools are installed by scripts/install-cli-tools.sh.

# Shell, search, Git and terminal utilities.
brew "chezmoi"
brew "git"
brew "git-lfs"
brew "gh"
brew "jj"
brew "mercurial"
brew "neovim"
brew "helix"
brew "lazygit"
brew "jq"
brew "ripgrep"
brew "fd"
brew "fzf"
brew "bat"
brew "eza"
brew "lsd"
brew "direnv"
brew "zoxide"
brew "btop"
brew "hyperfine"
brew "tokei"
brew "tlrc" # Provides tldr; the old tldr formula is disabled.
brew "fastfetch"
brew "inxi"
brew "screenfetch"
brew "clock-rs"
brew "ksh93"
brew "zsh"
brew "powerlevel10k"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "zsh-completions"

# GNU command flags used by Linux scripts; expose opt/*/libexec/gnubin in Zsh.
brew "coreutils"
brew "findutils"
brew "gnu-sed"
brew "gnu-tar"
brew "grep"
brew "gawk"
brew "gnu-getopt"
brew "diffutils"
brew "gzip"
brew "make"
brew "curl"
brew "wget"
brew "rsync"
brew "zip"
brew "unzip"
brew "sevenzip"
brew "unar"
brew "lzip"

# Cloud, networking, storage and AI command lines.
brew "awscli"
brew "rclone"
brew "nmap" # Includes ncat.
brew "gnupg"
brew "wireguard-tools"
brew "tailscale"
brew "googleworkspace-cli" # gws
brew "herdr"
brew "ollama"
brew "agent-browser"
brew "kimi-code"

# Runtimes and language tools. Java is discovered with java_home, not a fixed path.
brew "node"
brew "nvm"
brew "bun"
brew "pnpm"
brew "corepack"
brew "typescript"
brew "uv"
brew "python@3.12"
brew "python@3.13"
brew "go"
brew "gopls"
brew "staticcheck"
brew "rustup"
brew "coursier"
brew "scala-cli"
brew "sbt"
brew "swiftly"
brew "llvm"
brew "lld"
brew "lldb"
brew "gcc"
brew "gdb"
brew "riscv64-elf-gcc"
brew "riscv64-elf-binutils"
brew "cmake"
brew "ninja"
brew "pkgconf"
brew "meson"
brew "bison"
brew "flex"
brew "cppcheck"
brew "doxygen"
brew "glslang"
brew "scdoc"
brew "gettext"

# Image, video, PDF and document processing.
brew "ffmpeg"
brew "ffmpegthumbnailer"
brew "imagemagick"
brew "graphviz"
brew "poppler"
brew "pandoc"
brew "libqalculate"
brew "potrace"
brew "jp2a"
brew "ohcount"
brew "osslsigncode"
brew "yt-dlp"
brew "mpv"
brew "qemu"
brew "texlive"

# Docker Desktop supplies docker, Compose, Buildx and the macOS daemon.
cask "docker-desktop"
cask "codex"
cask "claude-code"
cask "codexbar"
cask "android-platform-tools"
cask "sage" # The signed package also publishes /usr/local/bin/sage.
cask "temurin@17"
cask "temurin@25"
cask "ghostty"
cask "karabiner-elements"
cask "visual-studio-code"
cask "zed"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
