-- Generated by nwg-displays on 2026-10-07 at 15:02:56. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    mode = "3840x2160@60.0",
    position = "0x0",
    scale = 1.0,
    vrr = 0
})
hl.monitor({
    output = "DP-2",
    mode = "1920x1080@60.0",
    position = "3840x240",
    scale = 1,
    vrr = 0,
    transform = 1
})
