# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */
# /* wallust template - colors-hyprland */

$background = rgb(1C1E23)
$foreground = rgb(F5EAE0)
$color0 = rgb(42444A)
$color1 = rgb(0B1B2E)
$color2 = rgb(1F4461)
$color3 = rgb(614256)
$color4 = rgb(29597B)
$color5 = rgb(A4574E)
$color6 = rgb(AA927D)
$color7 = rgb(E8D8CA)
$color8 = rgb(A2978D)
$color9 = rgb(0F243E)
$color10 = rgb(295B82)
$color11 = rgb(815872)
$color12 = rgb(3677A4)
$color13 = rgb(DA7468)
$color14 = rgb(E2C2A6)
$color15 = rgb(E8D8CA)
